version: '3.5'

services:
  redis:
    image: redis:latest
    container_name: redis_fastapi_db
    ports:
      - "6379:6379"
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis-data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis_ui
    ports:
      - "8081:8001"
    depends_on:
      - redis

volumes:
  redis-data:
